//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;

    public partial class tblDeniedIPAddress
    {
        public int DeniedIPAddressID { get; set; }
        public string IPAddress { get; set; }
        public int MediaID { get; set; }
        public string Remarks { get; set; }
        public bool DELFG { get; set; }
        public Nullable<System.DateTime> CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }

        public string title { get; set; }

        public string STRCRTDT { get; set; }
        public string STRCRTDTTIME { get; set; }
        public string STRUPDDT { get; set; }
        public virtual tblMedia tblMedia { get; set; }
    }
}
