//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMediaViewLog
    {
        public int MediaViewLogID { get; set; }
        public int MediaID { get; set; }

        
        public string UserName { get; set; }
        public string ClientIP { get; set; }
        public string UserAgent { get; set; }
        public bool DELFG { get; set; }
        public System.DateTime CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }
        public string StoreIPAddress { get; set; }
        public string StoreName { get; set; }
        public int StoreID { get; set; }
        public Nullable<int> FormatID { get; set; }

        public string FormatName { get; set; }
        public Nullable<DateTime> DateTime { get; set; }
        public Nullable<int> ClientSubnetID { get; set; }
        public virtual tblMedia tblMedia { get; set; }

        public string STRCRTDT { get; set; }
        public string STRCRTDTTIME { get; set; }
        public string STRUPDDT { get; set; }
    }

    public class playVideoDetails
    {
        public int MediaID { get; set; }

        public int FolderID { get; set; }
        public string Description { get; set; }
        public string Video { get; set; }
        public string Thumbnail { get; set; }
        public string Title { get; set; }
        public int ViewCount { get; set; }

        public string PlayVideoFileName { get; set; }

    }
}
