//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujiStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStoreSubnet
    {
        public int StoreSubnetID { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblStoreSubnetSubnetStore), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblStoreSubnetStoreDataAnnaValida1))]
        public int Store { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.Store), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblStoreSubnetSubnetDataAnnaValida1))]
        public int Subnet { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.CommonDelFlg), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }
        public Nullable<System.DateTime> CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetSNIPAddres), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string IPAddress { get; set; }
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblStoreSubnetSubnetSubnet), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string StoreName { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.StoreNumber), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string StoreNumber { get; set; }

        public virtual tblStore tblStore { get; set; }
        public virtual tblSubnet tblSubnet { get; set; }

        public int page { get; set; }
    }
    public class tblStoreSubnetReg
    {
        
        [Display(Name = nameof(MujiStore.Resources.Resource.CommonDelFlg), ResourceType = typeof(MujiStore.Resources.Resource))]
        public bool DELFG { get; set; }
        public Nullable<System.DateTime> CRTDT { get; set; }
        public string CRTCD { get; set; }
        public Nullable<System.DateTime> UPDDT { get; set; }
        public string UPDCD { get; set; }
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetSNIPAddres), ResourceType = typeof(MujiStore.Resources.Resource))]
        public string IPAddress { get; set; }

        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblStoreStoreNameDataAnnaValida1))]
        [MaxLength(250, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.CommonDataAnna0of1))]
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblStoreStoreName), ResourceType = typeof(MujiStore.Resources.Resource))]

        public string StoreName { get; set; }

        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.Pleaseenterthestorenumber))]
              

        [Display(Name = nameof(MujiStore.Resources.Resource.StoreNumber), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Range(1, 999999, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblStoreNumberMaxvalue))]
        public string StoreNumber { get; set; }

        

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblStoreStoreGroupID), ResourceType = typeof(MujiStore.Resources.Resource))]
        public Nullable<int> StoreGroupID { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetSNIPAddres), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetSNIPAddressDataAnnaValida1))]
        [RegularExpression(@"^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])){3}$", ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetSNIPAddressDataAnnaValida2))]
        public string SNIPAddress { get; set; }

        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetSubMask), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetSubMaskDataAnnaValida1))]
        [RegularExpression(@"^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])){3}$", ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetSubMaskDataAnnaValida2))]
        public string SubnetMask { get; set; }



        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.LanBanRequired))]
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetLANBandW), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Range(1, 50000000, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetLANBandWDataAnnaValida2))]
        public string LANBandWidth { get; set; }

        [Required(ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.WanBanRequired))]
        [Display(Name = nameof(MujiStore.Resources.Resource.ModtblSubnetWANBandW), ResourceType = typeof(MujiStore.Resources.Resource))]
        [Range(1, 50000000, ErrorMessageResourceType = typeof(MujiStore.Resources.Resource), ErrorMessageResourceName = nameof(MujiStore.Resources.Resource.ModtblSubnetWANBandWDataAnnaValida2))]
        public string WANBandWidth { get; set; }
    }
}
