Imports System
Imports DataDynamics.ActiveReports
Imports DataDynamics.ActiveReports.Document

Public Class R_Azukari_Sheet
    Inherits ActiveReport

    Dim DtView1 As DataView
    Dim i As Integer

    Public Sub New()
        MyBase.New()
        InitializeReport()

        'ïtëÆïi
        DtView1 = New DataView(P_DsPRT.Tables("Print02"), "", "", DataViewRowState.CurrentRows)
        If DtView1.Count <> 0 Then
            For i = 0 To DtView1.Count - 1
                Select Case i
                    Case Is = 0
                        Label003.Text = Label003.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label103.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 1
                        Label004.Text = Label004.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label104.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 2
                        Label005.Text = Label005.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label105.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 3
                        Label006.Text = Label006.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label106.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 4
                        Label009.Text = Label009.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label109.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 5
                        Label010.Text = Label010.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label110.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 6
                        Label011.Text = Label011.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label111.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 7
                        Label012.Text = Label012.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label112.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 8
                        Label015.Text = Label015.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label115.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 9
                        Label016.Text = Label016.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label116.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 10
                        Label017.Text = Label017.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label117.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 11
                        Label018.Text = Label018.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label118.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 12
                        Label021.Text = Label021.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label121.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 13
                        Label022.Text = Label022.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label122.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 14
                        Label023.Text = Label023.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label123.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 15
                        Label024.Text = Label024.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label124.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 16
                        Label027.Text = Label027.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label127.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 17
                        Label028.Text = Label028.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label128.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 18
                        Label029.Text = Label029.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label129.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                    Case Is = 19
                        Label030.Text = Label030.Text & DtView1(i)("item_name")
                        If DtView1(i)("amnt") <> 0 Then Label130.Text = DtView1(i)("amnt") & DtView1(i)("item_unit")
                End Select
            Next
        End If

        'èCóùì‡óe
        DtView1 = New DataView(P_DsPRT.Tables("Print03"), "", "", DataViewRowState.CurrentRows)
        If DtView1.Count <> 0 Then
            For i = 0 To DtView1.Count - 1
                If i = 0 Then
                    TextBox15.Text = DtView1(i)("cmnt")
                Else
                    TextBox15.Text = TextBox15.Text & System.Environment.NewLine & DtView1(i)("cmnt")
                End If
            Next
        End If

    End Sub
#Region "ActiveReports Designer generated code"
    Private WithEvents PageHeader As DataDynamics.ActiveReports.PageHeader = Nothing
    Private WithEvents Detail As DataDynamics.ActiveReports.Detail = Nothing
    Private WithEvents PageFooter As DataDynamics.ActiveReports.PageFooter = Nothing
	Private TextBox64 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label26 As DataDynamics.ActiveReports.Label = Nothing
	Private TextBox63 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label66 As DataDynamics.ActiveReports.Label = Nothing
	Private Label25 As DataDynamics.ActiveReports.Label = Nothing
	Private TextBox62 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox22 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox33 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox46 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox53 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox52 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox50 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox51 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox21 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox19 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox14 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox17 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox12 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox49 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox40 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox38 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox18 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox13 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox16 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox30 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label20 As DataDynamics.ActiveReports.Label = Nothing
	Private TextBox6 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox28 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label19 As DataDynamics.ActiveReports.Label = Nothing
	Private Label030 As DataDynamics.ActiveReports.Label = Nothing
	Private Label029 As DataDynamics.ActiveReports.Label = Nothing
	Private Label028 As DataDynamics.ActiveReports.Label = Nothing
	Private Label027 As DataDynamics.ActiveReports.Label = Nothing
	Private Label024 As DataDynamics.ActiveReports.Label = Nothing
	Private Label023 As DataDynamics.ActiveReports.Label = Nothing
	Private Label022 As DataDynamics.ActiveReports.Label = Nothing
	Private Label021 As DataDynamics.ActiveReports.Label = Nothing
	Private Label018 As DataDynamics.ActiveReports.Label = Nothing
	Private Label017 As DataDynamics.ActiveReports.Label = Nothing
	Private Label016 As DataDynamics.ActiveReports.Label = Nothing
	Private Label015 As DataDynamics.ActiveReports.Label = Nothing
	Private Label012 As DataDynamics.ActiveReports.Label = Nothing
	Private Label011 As DataDynamics.ActiveReports.Label = Nothing
	Private Label010 As DataDynamics.ActiveReports.Label = Nothing
	Private Label009 As DataDynamics.ActiveReports.Label = Nothing
	Private Label006 As DataDynamics.ActiveReports.Label = Nothing
	Private Label005 As DataDynamics.ActiveReports.Label = Nothing
	Private Label004 As DataDynamics.ActiveReports.Label = Nothing
	Private Label003 As DataDynamics.ActiveReports.Label = Nothing
	Private TextBox1 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label4 As DataDynamics.ActiveReports.Label = Nothing
	Private Label1 As DataDynamics.ActiveReports.Label = Nothing
	Private Label9 As DataDynamics.ActiveReports.Label = Nothing
	Private TextBox10 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox15 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Line11 As DataDynamics.ActiveReports.Line = Nothing
	Private Line16 As DataDynamics.ActiveReports.Line = Nothing
	Private Label As DataDynamics.ActiveReports.Label = Nothing
	Private TextBox4 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox23 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox25 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox27 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox29 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox31 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox34 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox41 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox43 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox45 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox47 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox48 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox56 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Line19 As DataDynamics.ActiveReports.Line = Nothing
	Private Line20 As DataDynamics.ActiveReports.Line = Nothing
	Private Line33 As DataDynamics.ActiveReports.Line = Nothing
	Private Line39 As DataDynamics.ActiveReports.Line = Nothing
	Private Line41 As DataDynamics.ActiveReports.Line = Nothing
	Private Line42 As DataDynamics.ActiveReports.Line = Nothing
	Private Line43 As DataDynamics.ActiveReports.Line = Nothing
	Private Line44 As DataDynamics.ActiveReports.Line = Nothing
	Private TextBox104 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox2 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox3 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox5 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox7 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox8 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox11 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox20 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Line5 As DataDynamics.ActiveReports.Line = Nothing
	Private Line7 As DataDynamics.ActiveReports.Line = Nothing
	Private Line8 As DataDynamics.ActiveReports.Line = Nothing
	Private Line9 As DataDynamics.ActiveReports.Line = Nothing
	Private Line10 As DataDynamics.ActiveReports.Line = Nothing
	Private Line12 As DataDynamics.ActiveReports.Line = Nothing
	Private Line13 As DataDynamics.ActiveReports.Line = Nothing
	Private Line75 As DataDynamics.ActiveReports.Line = Nothing
	Private Line82 As DataDynamics.ActiveReports.Line = Nothing
	Private Label2 As DataDynamics.ActiveReports.Label = Nothing
	Private Label3 As DataDynamics.ActiveReports.Label = Nothing
	Private Label5 As DataDynamics.ActiveReports.Label = Nothing
	Private Label6 As DataDynamics.ActiveReports.Label = Nothing
	Private Label7 As DataDynamics.ActiveReports.Label = Nothing
	Private Label8 As DataDynamics.ActiveReports.Label = Nothing
	Private Label10 As DataDynamics.ActiveReports.Label = Nothing
	Private Label11 As DataDynamics.ActiveReports.Label = Nothing
	Private Label12 As DataDynamics.ActiveReports.Label = Nothing
	Private Label13 As DataDynamics.ActiveReports.Label = Nothing
	Private Label14 As DataDynamics.ActiveReports.Label = Nothing
	Private Label15 As DataDynamics.ActiveReports.Label = Nothing
	Private Label16 As DataDynamics.ActiveReports.Label = Nothing
	Private Label47 As DataDynamics.ActiveReports.Label = Nothing
	Private Label48 As DataDynamics.ActiveReports.Label = Nothing
	Private Label49 As DataDynamics.ActiveReports.Label = Nothing
	Private Label50 As DataDynamics.ActiveReports.Label = Nothing
	Private Label51 As DataDynamics.ActiveReports.Label = Nothing
	Private Label52 As DataDynamics.ActiveReports.Label = Nothing
	Private Label53 As DataDynamics.ActiveReports.Label = Nothing
	Private Label54 As DataDynamics.ActiveReports.Label = Nothing
	Private TextBox9 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label56 As DataDynamics.ActiveReports.Label = Nothing
	Private Label57 As DataDynamics.ActiveReports.Label = Nothing
	Private Label58 As DataDynamics.ActiveReports.Label = Nothing
	Private Label59 As DataDynamics.ActiveReports.Label = Nothing
	Private Label60 As DataDynamics.ActiveReports.Label = Nothing
	Private Label61 As DataDynamics.ActiveReports.Label = Nothing
	Private Label62 As DataDynamics.ActiveReports.Label = Nothing
	Private Label63 As DataDynamics.ActiveReports.Label = Nothing
	Private Label64 As DataDynamics.ActiveReports.Label = Nothing
	Private Label65 As DataDynamics.ActiveReports.Label = Nothing
	Private Line14 As DataDynamics.ActiveReports.Line = Nothing
	Private Line15 As DataDynamics.ActiveReports.Line = Nothing
	Private Line17 As DataDynamics.ActiveReports.Line = Nothing
	Private Line18 As DataDynamics.ActiveReports.Line = Nothing
	Private Line21 As DataDynamics.ActiveReports.Line = Nothing
	Private Line22 As DataDynamics.ActiveReports.Line = Nothing
	Private Line23 As DataDynamics.ActiveReports.Line = Nothing
	Private Line24 As DataDynamics.ActiveReports.Line = Nothing
	Private Line25 As DataDynamics.ActiveReports.Line = Nothing
	Private Line26 As DataDynamics.ActiveReports.Line = Nothing
	Private Line27 As DataDynamics.ActiveReports.Line = Nothing
	Private Line28 As DataDynamics.ActiveReports.Line = Nothing
	Private Line30 As DataDynamics.ActiveReports.Line = Nothing
	Private Line31 As DataDynamics.ActiveReports.Line = Nothing
	Private Line32 As DataDynamics.ActiveReports.Line = Nothing
	Private Line35 As DataDynamics.ActiveReports.Line = Nothing
	Private Line36 As DataDynamics.ActiveReports.Line = Nothing
	Private Line37 As DataDynamics.ActiveReports.Line = Nothing
	Private Line38 As DataDynamics.ActiveReports.Line = Nothing
	Private Line40 As DataDynamics.ActiveReports.Line = Nothing
	Private Line45 As DataDynamics.ActiveReports.Line = Nothing
	Private Line46 As DataDynamics.ActiveReports.Line = Nothing
	Private Line47 As DataDynamics.ActiveReports.Line = Nothing
	Private Line48 As DataDynamics.ActiveReports.Line = Nothing
	Private Line49 As DataDynamics.ActiveReports.Line = Nothing
	Private Line50 As DataDynamics.ActiveReports.Line = Nothing
	Private Line51 As DataDynamics.ActiveReports.Line = Nothing
	Private Line52 As DataDynamics.ActiveReports.Line = Nothing
	Private Line53 As DataDynamics.ActiveReports.Line = Nothing
	Private Line55 As DataDynamics.ActiveReports.Line = Nothing
	Private Line56 As DataDynamics.ActiveReports.Line = Nothing
	Private Line57 As DataDynamics.ActiveReports.Line = Nothing
	Private Line58 As DataDynamics.ActiveReports.Line = Nothing
	Private Line59 As DataDynamics.ActiveReports.Line = Nothing
	Private Line60 As DataDynamics.ActiveReports.Line = Nothing
	Private Line61 As DataDynamics.ActiveReports.Line = Nothing
	Private Line68 As DataDynamics.ActiveReports.Line = Nothing
	Private Line69 As DataDynamics.ActiveReports.Line = Nothing
	Private Line70 As DataDynamics.ActiveReports.Line = Nothing
	Private Line71 As DataDynamics.ActiveReports.Line = Nothing
	Private Line72 As DataDynamics.ActiveReports.Line = Nothing
	Private Line73 As DataDynamics.ActiveReports.Line = Nothing
	Private Line74 As DataDynamics.ActiveReports.Line = Nothing
	Private Line79 As DataDynamics.ActiveReports.Line = Nothing
	Private Line80 As DataDynamics.ActiveReports.Line = Nothing
	Private Line81 As DataDynamics.ActiveReports.Line = Nothing
	Private Line83 As DataDynamics.ActiveReports.Line = Nothing
	Private Line84 As DataDynamics.ActiveReports.Line = Nothing
	Private Line85 As DataDynamics.ActiveReports.Line = Nothing
	Private Line86 As DataDynamics.ActiveReports.Line = Nothing
	Private Line87 As DataDynamics.ActiveReports.Line = Nothing
	Private Line88 As DataDynamics.ActiveReports.Line = Nothing
	Private Line89 As DataDynamics.ActiveReports.Line = Nothing
	Private Line92 As DataDynamics.ActiveReports.Line = Nothing
	Private TextBox24 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox26 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label103 As DataDynamics.ActiveReports.Label = Nothing
	Private Label104 As DataDynamics.ActiveReports.Label = Nothing
	Private Label105 As DataDynamics.ActiveReports.Label = Nothing
	Private Label106 As DataDynamics.ActiveReports.Label = Nothing
	Private Label112 As DataDynamics.ActiveReports.Label = Nothing
	Private Label111 As DataDynamics.ActiveReports.Label = Nothing
	Private Label110 As DataDynamics.ActiveReports.Label = Nothing
	Private Label109 As DataDynamics.ActiveReports.Label = Nothing
	Private Label115 As DataDynamics.ActiveReports.Label = Nothing
	Private Label116 As DataDynamics.ActiveReports.Label = Nothing
	Private Label117 As DataDynamics.ActiveReports.Label = Nothing
	Private Label118 As DataDynamics.ActiveReports.Label = Nothing
	Private Label121 As DataDynamics.ActiveReports.Label = Nothing
	Private Label122 As DataDynamics.ActiveReports.Label = Nothing
	Private Label123 As DataDynamics.ActiveReports.Label = Nothing
	Private Label124 As DataDynamics.ActiveReports.Label = Nothing
	Private Label127 As DataDynamics.ActiveReports.Label = Nothing
	Private Label128 As DataDynamics.ActiveReports.Label = Nothing
	Private Label129 As DataDynamics.ActiveReports.Label = Nothing
	Private Label130 As DataDynamics.ActiveReports.Label = Nothing
	Private Line54 As DataDynamics.ActiveReports.Line = Nothing
	Private Line62 As DataDynamics.ActiveReports.Line = Nothing
	Private Line63 As DataDynamics.ActiveReports.Line = Nothing
	Private Line65 As DataDynamics.ActiveReports.Line = Nothing
	Private Line64 As DataDynamics.ActiveReports.Line = Nothing
	Private Line66 As DataDynamics.ActiveReports.Line = Nothing
	Private Line34 As DataDynamics.ActiveReports.Line = Nothing
	Private Line67 As DataDynamics.ActiveReports.Line = Nothing
	Private Line2 As DataDynamics.ActiveReports.Line = Nothing
	Private TextBox36 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox39 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox44 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox57 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox59 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox61 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Line93 As DataDynamics.ActiveReports.Line = Nothing
	Private Line94 As DataDynamics.ActiveReports.Line = Nothing
	Private Line1 As DataDynamics.ActiveReports.Line = Nothing
	Private Line3 As DataDynamics.ActiveReports.Line = Nothing
	Private TextBox42 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox60 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox58 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox37 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox55 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox35 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox54 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox32 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Line90 As DataDynamics.ActiveReports.Line = Nothing
	Private Line91 As DataDynamics.ActiveReports.Line = Nothing
	Private Line77 As DataDynamics.ActiveReports.Line = Nothing
	Private Line78 As DataDynamics.ActiveReports.Line = Nothing
	Private Line76 As DataDynamics.ActiveReports.Line = Nothing
	Private Line As DataDynamics.ActiveReports.Line = Nothing
	Private Line29 As DataDynamics.ActiveReports.Line = Nothing
	Private Line4 As DataDynamics.ActiveReports.Line = Nothing
	Private Line6 As DataDynamics.ActiveReports.Line = Nothing
	Private Barcode1 As DataDynamics.ActiveReports.Barcode = Nothing
	Private Barcode2 As DataDynamics.ActiveReports.Barcode = Nothing
	Private Barcode3 As DataDynamics.ActiveReports.Barcode = Nothing
	Private Barcode4 As DataDynamics.ActiveReports.Barcode = Nothing
	Private TextBox65 As DataDynamics.ActiveReports.TextBox = Nothing
	Private Barcode5 As DataDynamics.ActiveReports.Barcode = Nothing
	Private Barcode6 As DataDynamics.ActiveReports.Barcode = Nothing
	Private Barcode As DataDynamics.ActiveReports.Barcode = Nothing
	Private Barcode7 As DataDynamics.ActiveReports.Barcode = Nothing
	Private TextBox66 As DataDynamics.ActiveReports.TextBox = Nothing
	Private TextBox67 As DataDynamics.ActiveReports.TextBox = Nothing
	Public Sub InitializeReport()
		Me.LoadLayout(Me.GetType, "nMVAR.R_Azukari_Sheet.rpx")
		Me.PageHeader = CType(Me.Sections("PageHeader"),DataDynamics.ActiveReports.PageHeader)
		Me.Detail = CType(Me.Sections("Detail"),DataDynamics.ActiveReports.Detail)
		Me.PageFooter = CType(Me.Sections("PageFooter"),DataDynamics.ActiveReports.PageFooter)
		Me.TextBox64 = CType(Me.Detail.Controls(0),DataDynamics.ActiveReports.TextBox)
		Me.Label26 = CType(Me.Detail.Controls(1),DataDynamics.ActiveReports.Label)
		Me.TextBox63 = CType(Me.Detail.Controls(2),DataDynamics.ActiveReports.TextBox)
		Me.Label66 = CType(Me.Detail.Controls(3),DataDynamics.ActiveReports.Label)
		Me.Label25 = CType(Me.Detail.Controls(4),DataDynamics.ActiveReports.Label)
		Me.TextBox62 = CType(Me.Detail.Controls(5),DataDynamics.ActiveReports.TextBox)
		Me.TextBox22 = CType(Me.Detail.Controls(6),DataDynamics.ActiveReports.TextBox)
		Me.TextBox33 = CType(Me.Detail.Controls(7),DataDynamics.ActiveReports.TextBox)
		Me.TextBox46 = CType(Me.Detail.Controls(8),DataDynamics.ActiveReports.TextBox)
		Me.TextBox53 = CType(Me.Detail.Controls(9),DataDynamics.ActiveReports.TextBox)
		Me.TextBox52 = CType(Me.Detail.Controls(10),DataDynamics.ActiveReports.TextBox)
		Me.TextBox50 = CType(Me.Detail.Controls(11),DataDynamics.ActiveReports.TextBox)
		Me.TextBox51 = CType(Me.Detail.Controls(12),DataDynamics.ActiveReports.TextBox)
		Me.TextBox21 = CType(Me.Detail.Controls(13),DataDynamics.ActiveReports.TextBox)
		Me.TextBox19 = CType(Me.Detail.Controls(14),DataDynamics.ActiveReports.TextBox)
		Me.TextBox14 = CType(Me.Detail.Controls(15),DataDynamics.ActiveReports.TextBox)
		Me.TextBox17 = CType(Me.Detail.Controls(16),DataDynamics.ActiveReports.TextBox)
		Me.TextBox12 = CType(Me.Detail.Controls(17),DataDynamics.ActiveReports.TextBox)
		Me.TextBox49 = CType(Me.Detail.Controls(18),DataDynamics.ActiveReports.TextBox)
		Me.TextBox40 = CType(Me.Detail.Controls(19),DataDynamics.ActiveReports.TextBox)
		Me.TextBox38 = CType(Me.Detail.Controls(20),DataDynamics.ActiveReports.TextBox)
		Me.TextBox18 = CType(Me.Detail.Controls(21),DataDynamics.ActiveReports.TextBox)
		Me.TextBox13 = CType(Me.Detail.Controls(22),DataDynamics.ActiveReports.TextBox)
		Me.TextBox16 = CType(Me.Detail.Controls(23),DataDynamics.ActiveReports.TextBox)
		Me.TextBox30 = CType(Me.Detail.Controls(24),DataDynamics.ActiveReports.TextBox)
		Me.Label20 = CType(Me.Detail.Controls(25),DataDynamics.ActiveReports.Label)
		Me.TextBox6 = CType(Me.Detail.Controls(26),DataDynamics.ActiveReports.TextBox)
		Me.TextBox28 = CType(Me.Detail.Controls(27),DataDynamics.ActiveReports.TextBox)
		Me.Label19 = CType(Me.Detail.Controls(28),DataDynamics.ActiveReports.Label)
		Me.Label030 = CType(Me.Detail.Controls(29),DataDynamics.ActiveReports.Label)
		Me.Label029 = CType(Me.Detail.Controls(30),DataDynamics.ActiveReports.Label)
		Me.Label028 = CType(Me.Detail.Controls(31),DataDynamics.ActiveReports.Label)
		Me.Label027 = CType(Me.Detail.Controls(32),DataDynamics.ActiveReports.Label)
		Me.Label024 = CType(Me.Detail.Controls(33),DataDynamics.ActiveReports.Label)
		Me.Label023 = CType(Me.Detail.Controls(34),DataDynamics.ActiveReports.Label)
		Me.Label022 = CType(Me.Detail.Controls(35),DataDynamics.ActiveReports.Label)
		Me.Label021 = CType(Me.Detail.Controls(36),DataDynamics.ActiveReports.Label)
		Me.Label018 = CType(Me.Detail.Controls(37),DataDynamics.ActiveReports.Label)
		Me.Label017 = CType(Me.Detail.Controls(38),DataDynamics.ActiveReports.Label)
		Me.Label016 = CType(Me.Detail.Controls(39),DataDynamics.ActiveReports.Label)
		Me.Label015 = CType(Me.Detail.Controls(40),DataDynamics.ActiveReports.Label)
		Me.Label012 = CType(Me.Detail.Controls(41),DataDynamics.ActiveReports.Label)
		Me.Label011 = CType(Me.Detail.Controls(42),DataDynamics.ActiveReports.Label)
		Me.Label010 = CType(Me.Detail.Controls(43),DataDynamics.ActiveReports.Label)
		Me.Label009 = CType(Me.Detail.Controls(44),DataDynamics.ActiveReports.Label)
		Me.Label006 = CType(Me.Detail.Controls(45),DataDynamics.ActiveReports.Label)
		Me.Label005 = CType(Me.Detail.Controls(46),DataDynamics.ActiveReports.Label)
		Me.Label004 = CType(Me.Detail.Controls(47),DataDynamics.ActiveReports.Label)
		Me.Label003 = CType(Me.Detail.Controls(48),DataDynamics.ActiveReports.Label)
		Me.TextBox1 = CType(Me.Detail.Controls(49),DataDynamics.ActiveReports.TextBox)
		Me.Label4 = CType(Me.Detail.Controls(50),DataDynamics.ActiveReports.Label)
		Me.Label1 = CType(Me.Detail.Controls(51),DataDynamics.ActiveReports.Label)
		Me.Label9 = CType(Me.Detail.Controls(52),DataDynamics.ActiveReports.Label)
		Me.TextBox10 = CType(Me.Detail.Controls(53),DataDynamics.ActiveReports.TextBox)
		Me.TextBox15 = CType(Me.Detail.Controls(54),DataDynamics.ActiveReports.TextBox)
		Me.Line11 = CType(Me.Detail.Controls(55),DataDynamics.ActiveReports.Line)
		Me.Line16 = CType(Me.Detail.Controls(56),DataDynamics.ActiveReports.Line)
		Me.Label = CType(Me.Detail.Controls(57),DataDynamics.ActiveReports.Label)
		Me.TextBox4 = CType(Me.Detail.Controls(58),DataDynamics.ActiveReports.TextBox)
		Me.TextBox23 = CType(Me.Detail.Controls(59),DataDynamics.ActiveReports.TextBox)
		Me.TextBox25 = CType(Me.Detail.Controls(60),DataDynamics.ActiveReports.TextBox)
		Me.TextBox27 = CType(Me.Detail.Controls(61),DataDynamics.ActiveReports.TextBox)
		Me.TextBox29 = CType(Me.Detail.Controls(62),DataDynamics.ActiveReports.TextBox)
		Me.TextBox31 = CType(Me.Detail.Controls(63),DataDynamics.ActiveReports.TextBox)
		Me.TextBox34 = CType(Me.Detail.Controls(64),DataDynamics.ActiveReports.TextBox)
		Me.TextBox41 = CType(Me.Detail.Controls(65),DataDynamics.ActiveReports.TextBox)
		Me.TextBox43 = CType(Me.Detail.Controls(66),DataDynamics.ActiveReports.TextBox)
		Me.TextBox45 = CType(Me.Detail.Controls(67),DataDynamics.ActiveReports.TextBox)
		Me.TextBox47 = CType(Me.Detail.Controls(68),DataDynamics.ActiveReports.TextBox)
		Me.TextBox48 = CType(Me.Detail.Controls(69),DataDynamics.ActiveReports.TextBox)
		Me.TextBox56 = CType(Me.Detail.Controls(70),DataDynamics.ActiveReports.TextBox)
		Me.Line19 = CType(Me.Detail.Controls(71),DataDynamics.ActiveReports.Line)
		Me.Line20 = CType(Me.Detail.Controls(72),DataDynamics.ActiveReports.Line)
		Me.Line33 = CType(Me.Detail.Controls(73),DataDynamics.ActiveReports.Line)
		Me.Line39 = CType(Me.Detail.Controls(74),DataDynamics.ActiveReports.Line)
		Me.Line41 = CType(Me.Detail.Controls(75),DataDynamics.ActiveReports.Line)
		Me.Line42 = CType(Me.Detail.Controls(76),DataDynamics.ActiveReports.Line)
		Me.Line43 = CType(Me.Detail.Controls(77),DataDynamics.ActiveReports.Line)
		Me.Line44 = CType(Me.Detail.Controls(78),DataDynamics.ActiveReports.Line)
		Me.TextBox104 = CType(Me.Detail.Controls(79),DataDynamics.ActiveReports.TextBox)
		Me.TextBox = CType(Me.Detail.Controls(80),DataDynamics.ActiveReports.TextBox)
		Me.TextBox2 = CType(Me.Detail.Controls(81),DataDynamics.ActiveReports.TextBox)
		Me.TextBox3 = CType(Me.Detail.Controls(82),DataDynamics.ActiveReports.TextBox)
		Me.TextBox5 = CType(Me.Detail.Controls(83),DataDynamics.ActiveReports.TextBox)
		Me.TextBox7 = CType(Me.Detail.Controls(84),DataDynamics.ActiveReports.TextBox)
		Me.TextBox8 = CType(Me.Detail.Controls(85),DataDynamics.ActiveReports.TextBox)
		Me.TextBox11 = CType(Me.Detail.Controls(86),DataDynamics.ActiveReports.TextBox)
		Me.TextBox20 = CType(Me.Detail.Controls(87),DataDynamics.ActiveReports.TextBox)
		Me.Line5 = CType(Me.Detail.Controls(88),DataDynamics.ActiveReports.Line)
		Me.Line7 = CType(Me.Detail.Controls(89),DataDynamics.ActiveReports.Line)
		Me.Line8 = CType(Me.Detail.Controls(90),DataDynamics.ActiveReports.Line)
		Me.Line9 = CType(Me.Detail.Controls(91),DataDynamics.ActiveReports.Line)
		Me.Line10 = CType(Me.Detail.Controls(92),DataDynamics.ActiveReports.Line)
		Me.Line12 = CType(Me.Detail.Controls(93),DataDynamics.ActiveReports.Line)
		Me.Line13 = CType(Me.Detail.Controls(94),DataDynamics.ActiveReports.Line)
		Me.Line75 = CType(Me.Detail.Controls(95),DataDynamics.ActiveReports.Line)
		Me.Line82 = CType(Me.Detail.Controls(96),DataDynamics.ActiveReports.Line)
		Me.Label2 = CType(Me.Detail.Controls(97),DataDynamics.ActiveReports.Label)
		Me.Label3 = CType(Me.Detail.Controls(98),DataDynamics.ActiveReports.Label)
		Me.Label5 = CType(Me.Detail.Controls(99),DataDynamics.ActiveReports.Label)
		Me.Label6 = CType(Me.Detail.Controls(100),DataDynamics.ActiveReports.Label)
		Me.Label7 = CType(Me.Detail.Controls(101),DataDynamics.ActiveReports.Label)
		Me.Label8 = CType(Me.Detail.Controls(102),DataDynamics.ActiveReports.Label)
		Me.Label10 = CType(Me.Detail.Controls(103),DataDynamics.ActiveReports.Label)
		Me.Label11 = CType(Me.Detail.Controls(104),DataDynamics.ActiveReports.Label)
		Me.Label12 = CType(Me.Detail.Controls(105),DataDynamics.ActiveReports.Label)
		Me.Label13 = CType(Me.Detail.Controls(106),DataDynamics.ActiveReports.Label)
		Me.Label14 = CType(Me.Detail.Controls(107),DataDynamics.ActiveReports.Label)
		Me.Label15 = CType(Me.Detail.Controls(108),DataDynamics.ActiveReports.Label)
		Me.Label16 = CType(Me.Detail.Controls(109),DataDynamics.ActiveReports.Label)
		Me.Label47 = CType(Me.Detail.Controls(110),DataDynamics.ActiveReports.Label)
		Me.Label48 = CType(Me.Detail.Controls(111),DataDynamics.ActiveReports.Label)
		Me.Label49 = CType(Me.Detail.Controls(112),DataDynamics.ActiveReports.Label)
		Me.Label50 = CType(Me.Detail.Controls(113),DataDynamics.ActiveReports.Label)
		Me.Label51 = CType(Me.Detail.Controls(114),DataDynamics.ActiveReports.Label)
		Me.Label52 = CType(Me.Detail.Controls(115),DataDynamics.ActiveReports.Label)
		Me.Label53 = CType(Me.Detail.Controls(116),DataDynamics.ActiveReports.Label)
		Me.Label54 = CType(Me.Detail.Controls(117),DataDynamics.ActiveReports.Label)
		Me.TextBox9 = CType(Me.Detail.Controls(118),DataDynamics.ActiveReports.TextBox)
		Me.Label56 = CType(Me.Detail.Controls(119),DataDynamics.ActiveReports.Label)
		Me.Label57 = CType(Me.Detail.Controls(120),DataDynamics.ActiveReports.Label)
		Me.Label58 = CType(Me.Detail.Controls(121),DataDynamics.ActiveReports.Label)
		Me.Label59 = CType(Me.Detail.Controls(122),DataDynamics.ActiveReports.Label)
		Me.Label60 = CType(Me.Detail.Controls(123),DataDynamics.ActiveReports.Label)
		Me.Label61 = CType(Me.Detail.Controls(124),DataDynamics.ActiveReports.Label)
		Me.Label62 = CType(Me.Detail.Controls(125),DataDynamics.ActiveReports.Label)
		Me.Label63 = CType(Me.Detail.Controls(126),DataDynamics.ActiveReports.Label)
		Me.Label64 = CType(Me.Detail.Controls(127),DataDynamics.ActiveReports.Label)
		Me.Label65 = CType(Me.Detail.Controls(128),DataDynamics.ActiveReports.Label)
		Me.Line14 = CType(Me.Detail.Controls(129),DataDynamics.ActiveReports.Line)
		Me.Line15 = CType(Me.Detail.Controls(130),DataDynamics.ActiveReports.Line)
		Me.Line17 = CType(Me.Detail.Controls(131),DataDynamics.ActiveReports.Line)
		Me.Line18 = CType(Me.Detail.Controls(132),DataDynamics.ActiveReports.Line)
		Me.Line21 = CType(Me.Detail.Controls(133),DataDynamics.ActiveReports.Line)
		Me.Line22 = CType(Me.Detail.Controls(134),DataDynamics.ActiveReports.Line)
		Me.Line23 = CType(Me.Detail.Controls(135),DataDynamics.ActiveReports.Line)
		Me.Line24 = CType(Me.Detail.Controls(136),DataDynamics.ActiveReports.Line)
		Me.Line25 = CType(Me.Detail.Controls(137),DataDynamics.ActiveReports.Line)
		Me.Line26 = CType(Me.Detail.Controls(138),DataDynamics.ActiveReports.Line)
		Me.Line27 = CType(Me.Detail.Controls(139),DataDynamics.ActiveReports.Line)
		Me.Line28 = CType(Me.Detail.Controls(140),DataDynamics.ActiveReports.Line)
		Me.Line30 = CType(Me.Detail.Controls(141),DataDynamics.ActiveReports.Line)
		Me.Line31 = CType(Me.Detail.Controls(142),DataDynamics.ActiveReports.Line)
		Me.Line32 = CType(Me.Detail.Controls(143),DataDynamics.ActiveReports.Line)
		Me.Line35 = CType(Me.Detail.Controls(144),DataDynamics.ActiveReports.Line)
		Me.Line36 = CType(Me.Detail.Controls(145),DataDynamics.ActiveReports.Line)
		Me.Line37 = CType(Me.Detail.Controls(146),DataDynamics.ActiveReports.Line)
		Me.Line38 = CType(Me.Detail.Controls(147),DataDynamics.ActiveReports.Line)
		Me.Line40 = CType(Me.Detail.Controls(148),DataDynamics.ActiveReports.Line)
		Me.Line45 = CType(Me.Detail.Controls(149),DataDynamics.ActiveReports.Line)
		Me.Line46 = CType(Me.Detail.Controls(150),DataDynamics.ActiveReports.Line)
		Me.Line47 = CType(Me.Detail.Controls(151),DataDynamics.ActiveReports.Line)
		Me.Line48 = CType(Me.Detail.Controls(152),DataDynamics.ActiveReports.Line)
		Me.Line49 = CType(Me.Detail.Controls(153),DataDynamics.ActiveReports.Line)
		Me.Line50 = CType(Me.Detail.Controls(154),DataDynamics.ActiveReports.Line)
		Me.Line51 = CType(Me.Detail.Controls(155),DataDynamics.ActiveReports.Line)
		Me.Line52 = CType(Me.Detail.Controls(156),DataDynamics.ActiveReports.Line)
		Me.Line53 = CType(Me.Detail.Controls(157),DataDynamics.ActiveReports.Line)
		Me.Line55 = CType(Me.Detail.Controls(158),DataDynamics.ActiveReports.Line)
		Me.Line56 = CType(Me.Detail.Controls(159),DataDynamics.ActiveReports.Line)
		Me.Line57 = CType(Me.Detail.Controls(160),DataDynamics.ActiveReports.Line)
		Me.Line58 = CType(Me.Detail.Controls(161),DataDynamics.ActiveReports.Line)
		Me.Line59 = CType(Me.Detail.Controls(162),DataDynamics.ActiveReports.Line)
		Me.Line60 = CType(Me.Detail.Controls(163),DataDynamics.ActiveReports.Line)
		Me.Line61 = CType(Me.Detail.Controls(164),DataDynamics.ActiveReports.Line)
		Me.Line68 = CType(Me.Detail.Controls(165),DataDynamics.ActiveReports.Line)
		Me.Line69 = CType(Me.Detail.Controls(166),DataDynamics.ActiveReports.Line)
		Me.Line70 = CType(Me.Detail.Controls(167),DataDynamics.ActiveReports.Line)
		Me.Line71 = CType(Me.Detail.Controls(168),DataDynamics.ActiveReports.Line)
		Me.Line72 = CType(Me.Detail.Controls(169),DataDynamics.ActiveReports.Line)
		Me.Line73 = CType(Me.Detail.Controls(170),DataDynamics.ActiveReports.Line)
		Me.Line74 = CType(Me.Detail.Controls(171),DataDynamics.ActiveReports.Line)
		Me.Line79 = CType(Me.Detail.Controls(172),DataDynamics.ActiveReports.Line)
		Me.Line80 = CType(Me.Detail.Controls(173),DataDynamics.ActiveReports.Line)
		Me.Line81 = CType(Me.Detail.Controls(174),DataDynamics.ActiveReports.Line)
		Me.Line83 = CType(Me.Detail.Controls(175),DataDynamics.ActiveReports.Line)
		Me.Line84 = CType(Me.Detail.Controls(176),DataDynamics.ActiveReports.Line)
		Me.Line85 = CType(Me.Detail.Controls(177),DataDynamics.ActiveReports.Line)
		Me.Line86 = CType(Me.Detail.Controls(178),DataDynamics.ActiveReports.Line)
		Me.Line87 = CType(Me.Detail.Controls(179),DataDynamics.ActiveReports.Line)
		Me.Line88 = CType(Me.Detail.Controls(180),DataDynamics.ActiveReports.Line)
		Me.Line89 = CType(Me.Detail.Controls(181),DataDynamics.ActiveReports.Line)
		Me.Line92 = CType(Me.Detail.Controls(182),DataDynamics.ActiveReports.Line)
		Me.TextBox24 = CType(Me.Detail.Controls(183),DataDynamics.ActiveReports.TextBox)
		Me.TextBox26 = CType(Me.Detail.Controls(184),DataDynamics.ActiveReports.TextBox)
		Me.Label103 = CType(Me.Detail.Controls(185),DataDynamics.ActiveReports.Label)
		Me.Label104 = CType(Me.Detail.Controls(186),DataDynamics.ActiveReports.Label)
		Me.Label105 = CType(Me.Detail.Controls(187),DataDynamics.ActiveReports.Label)
		Me.Label106 = CType(Me.Detail.Controls(188),DataDynamics.ActiveReports.Label)
		Me.Label112 = CType(Me.Detail.Controls(189),DataDynamics.ActiveReports.Label)
		Me.Label111 = CType(Me.Detail.Controls(190),DataDynamics.ActiveReports.Label)
		Me.Label110 = CType(Me.Detail.Controls(191),DataDynamics.ActiveReports.Label)
		Me.Label109 = CType(Me.Detail.Controls(192),DataDynamics.ActiveReports.Label)
		Me.Label115 = CType(Me.Detail.Controls(193),DataDynamics.ActiveReports.Label)
		Me.Label116 = CType(Me.Detail.Controls(194),DataDynamics.ActiveReports.Label)
		Me.Label117 = CType(Me.Detail.Controls(195),DataDynamics.ActiveReports.Label)
		Me.Label118 = CType(Me.Detail.Controls(196),DataDynamics.ActiveReports.Label)
		Me.Label121 = CType(Me.Detail.Controls(197),DataDynamics.ActiveReports.Label)
		Me.Label122 = CType(Me.Detail.Controls(198),DataDynamics.ActiveReports.Label)
		Me.Label123 = CType(Me.Detail.Controls(199),DataDynamics.ActiveReports.Label)
		Me.Label124 = CType(Me.Detail.Controls(200),DataDynamics.ActiveReports.Label)
		Me.Label127 = CType(Me.Detail.Controls(201),DataDynamics.ActiveReports.Label)
		Me.Label128 = CType(Me.Detail.Controls(202),DataDynamics.ActiveReports.Label)
		Me.Label129 = CType(Me.Detail.Controls(203),DataDynamics.ActiveReports.Label)
		Me.Label130 = CType(Me.Detail.Controls(204),DataDynamics.ActiveReports.Label)
		Me.Line54 = CType(Me.Detail.Controls(205),DataDynamics.ActiveReports.Line)
		Me.Line62 = CType(Me.Detail.Controls(206),DataDynamics.ActiveReports.Line)
		Me.Line63 = CType(Me.Detail.Controls(207),DataDynamics.ActiveReports.Line)
		Me.Line65 = CType(Me.Detail.Controls(208),DataDynamics.ActiveReports.Line)
		Me.Line64 = CType(Me.Detail.Controls(209),DataDynamics.ActiveReports.Line)
		Me.Line66 = CType(Me.Detail.Controls(210),DataDynamics.ActiveReports.Line)
		Me.Line34 = CType(Me.Detail.Controls(211),DataDynamics.ActiveReports.Line)
		Me.Line67 = CType(Me.Detail.Controls(212),DataDynamics.ActiveReports.Line)
		Me.Line2 = CType(Me.Detail.Controls(213),DataDynamics.ActiveReports.Line)
		Me.TextBox36 = CType(Me.Detail.Controls(214),DataDynamics.ActiveReports.TextBox)
		Me.TextBox39 = CType(Me.Detail.Controls(215),DataDynamics.ActiveReports.TextBox)
		Me.TextBox44 = CType(Me.Detail.Controls(216),DataDynamics.ActiveReports.TextBox)
		Me.TextBox57 = CType(Me.Detail.Controls(217),DataDynamics.ActiveReports.TextBox)
		Me.TextBox59 = CType(Me.Detail.Controls(218),DataDynamics.ActiveReports.TextBox)
		Me.TextBox61 = CType(Me.Detail.Controls(219),DataDynamics.ActiveReports.TextBox)
		Me.Line93 = CType(Me.Detail.Controls(220),DataDynamics.ActiveReports.Line)
		Me.Line94 = CType(Me.Detail.Controls(221),DataDynamics.ActiveReports.Line)
		Me.Line1 = CType(Me.Detail.Controls(222),DataDynamics.ActiveReports.Line)
		Me.Line3 = CType(Me.Detail.Controls(223),DataDynamics.ActiveReports.Line)
		Me.TextBox42 = CType(Me.Detail.Controls(224),DataDynamics.ActiveReports.TextBox)
		Me.TextBox60 = CType(Me.Detail.Controls(225),DataDynamics.ActiveReports.TextBox)
		Me.TextBox58 = CType(Me.Detail.Controls(226),DataDynamics.ActiveReports.TextBox)
		Me.TextBox37 = CType(Me.Detail.Controls(227),DataDynamics.ActiveReports.TextBox)
		Me.TextBox55 = CType(Me.Detail.Controls(228),DataDynamics.ActiveReports.TextBox)
		Me.TextBox35 = CType(Me.Detail.Controls(229),DataDynamics.ActiveReports.TextBox)
		Me.TextBox54 = CType(Me.Detail.Controls(230),DataDynamics.ActiveReports.TextBox)
		Me.TextBox32 = CType(Me.Detail.Controls(231),DataDynamics.ActiveReports.TextBox)
		Me.Line90 = CType(Me.Detail.Controls(232),DataDynamics.ActiveReports.Line)
		Me.Line91 = CType(Me.Detail.Controls(233),DataDynamics.ActiveReports.Line)
		Me.Line77 = CType(Me.Detail.Controls(234),DataDynamics.ActiveReports.Line)
		Me.Line78 = CType(Me.Detail.Controls(235),DataDynamics.ActiveReports.Line)
		Me.Line76 = CType(Me.Detail.Controls(236),DataDynamics.ActiveReports.Line)
		Me.Line = CType(Me.Detail.Controls(237),DataDynamics.ActiveReports.Line)
		Me.Line29 = CType(Me.Detail.Controls(238),DataDynamics.ActiveReports.Line)
		Me.Line4 = CType(Me.Detail.Controls(239),DataDynamics.ActiveReports.Line)
		Me.Line6 = CType(Me.Detail.Controls(240),DataDynamics.ActiveReports.Line)
		Me.Barcode1 = CType(Me.Detail.Controls(241),DataDynamics.ActiveReports.Barcode)
		Me.Barcode2 = CType(Me.Detail.Controls(242),DataDynamics.ActiveReports.Barcode)
		Me.Barcode3 = CType(Me.Detail.Controls(243),DataDynamics.ActiveReports.Barcode)
		Me.Barcode4 = CType(Me.Detail.Controls(244),DataDynamics.ActiveReports.Barcode)
		Me.TextBox65 = CType(Me.Detail.Controls(245),DataDynamics.ActiveReports.TextBox)
		Me.Barcode5 = CType(Me.Detail.Controls(246),DataDynamics.ActiveReports.Barcode)
		Me.Barcode6 = CType(Me.Detail.Controls(247),DataDynamics.ActiveReports.Barcode)
		Me.Barcode = CType(Me.Detail.Controls(248),DataDynamics.ActiveReports.Barcode)
		Me.Barcode7 = CType(Me.Detail.Controls(249),DataDynamics.ActiveReports.Barcode)
		Me.TextBox66 = CType(Me.Detail.Controls(250),DataDynamics.ActiveReports.TextBox)
		Me.TextBox67 = CType(Me.Detail.Controls(251),DataDynamics.ActiveReports.TextBox)
	End Sub

#End Region

    Private Sub Detail_Format(ByVal sender As Object, ByVal e As System.EventArgs) Handles Detail.Format
        If TextBox65.Text = "3355" Or TextBox65.Text = "9210" Then
            Barcode1.Visible = True : Barcode2.Visible = True : Barcode3.Visible = True : Barcode4.Visible = True : Barcode5.Visible = True : Barcode6.Visible = True
            TextBox.Visible = False : TextBox7.Visible = False : TextBox11.Visible = False : TextBox3.Visible = False
            Label20.Visible = False : TextBox30.Visible = False : Line67.Visible = False
            TextBox10.Visible = False
        Else
            Barcode1.Visible = False : Barcode2.Visible = False : Barcode3.Visible = False : Barcode4.Visible = False : Barcode5.Visible = False : Barcode6.Visible = False
            TextBox.Visible = True : TextBox7.Visible = True : TextBox11.Visible = True : TextBox3.Visible = True
            Label20.Visible = True : TextBox30.Visible = True : Line67.Visible = True
            TextBox10.Visible = True
        End If
        If Trim(TextBox24.Text) <> Nothing Then TextBox15.Text = TextBox15.Text & System.Environment.NewLine & TextBox24.Text
        If Trim(TextBox26.Text) <> Nothing Then TextBox15.Text = TextBox15.Text & System.Environment.NewLine & TextBox26.Text
    End Sub
End Class