CREATE TABLE [dbo].[YREALIZATION](
	[YREALIZATION_PKID] [bigint] IDENTITY(1,1) NOT NULL,
	[VBELN] [varchar](10) NOT NULL,
	[VGBEL] [varchar](10) NOT NULL,
	[AUBEL] [varchar](10) NOT NULL,
	[ERDAT] [varchar](10) NOT NULL,
	[FKART] [varchar](4) NOT NULL,
	[REGIO] [varchar](3) NOT NULL,
	[VKGRP] [varchar](3) NOT NULL,
	[DSTRC] [varchar](4) NOT NULL,
	[MNFPLANT] [varchar](4) NOT NULL,
	[PLANT] [varchar](4) NOT NULL,
	[GRADE] [varchar](2) NOT NULL,
	[MATKL] [varchar](9) NOT NULL,
	[KALKS] [varchar](1) NOT NULL,
	[KDGRP] [varchar](2) NOT NULL,
	[FKDAT] [varchar](10) NOT NULL,
	[MATNR] [varchar](18) NOT NULL,
	[CUSTCODE1] [varchar](10) NOT NULL,
	[CNAME1] [varchar](35) NOT NULL,
	[CUSTCODE2] [varchar](10) NOT NULL,
	[CNAME2] [varchar](35) NOT NULL,
	[CUSTCODE3] [varchar](10) NOT NULL,
	[CNAME3] [varchar](35) NOT NULL,
	[COM_AG] [varchar](10) NOT NULL,
	[COM_NAME] [varchar](35) NOT NULL,
	[TRANS] [varchar](10) NOT NULL,
	[TRANS_NAME] [varchar](35) NOT NULL,
	[LGORT] [varchar](4) NOT NULL,
	[LGOBE] [varchar](16) NOT NULL,
	[FKIMG] [decimal](13, 3) NOT NULL,
	[GROSSTURN] [decimal](16, 3) NOT NULL,
	[INCO1] [varchar](3) NOT NULL,
	[INCO2] [varchar](28) NOT NULL,
	[STPRS] [decimal](12, 3) NOT NULL,
	[PRIMARYFRI] [decimal](16, 3) NOT NULL,
	[SECONDARYFRI] [decimal](16, 3) NOT NULL,
	[EXWPF] [decimal](16, 3) NOT NULL,
	[EXGSF] [decimal](16, 3) NOT NULL,
	[SALESTAX] [decimal](16, 3) NOT NULL,
	[COMMISSION] [decimal](16, 3) NOT NULL,
	[EXCISEDUTY] [decimal](16, 3) NOT NULL,
	[PDDISCOUNT] [decimal](16, 3) NOT NULL,
	[ODDISCOUNT] [decimal](16, 3) NOT NULL,
	[CFCHARGES] [decimal](16, 3) NOT NULL,
	[CDDISCOUNT] [decimal](16, 3) NOT NULL,
	[PACKING] [decimal](16, 3) NOT NULL,
	[UNLOADING] [decimal](16, 3) NOT NULL,
	[OCTRAI] [decimal](16, 3) NOT NULL,
	[VAT] [decimal](16, 3) NOT NULL,
	[IGST] [decimal](16, 3) NOT NULL,
	[CGST] [decimal](16, 3) NOT NULL,
	[SGST] [decimal](16, 3) NOT NULL,
	[UGST] [decimal](16, 3) NOT NULL,
	[EXP_HAND] [decimal](16, 3) NOT NULL,
	[TRANSPORT] [decimal](16, 3) NOT NULL,
	[AMT_DW_FRT] [decimal](16, 3) NOT NULL,
	[PLT_FRT] [decimal](16, 3) NOT NULL,
	[NETTURN] [decimal](16, 3) NOT NULL,
	[NAKEDREAL] [decimal](16, 3) NOT NULL,
	[STATEDESC] [varchar](20) NOT NULL,
	[SGRPDESC] [varchar](20) NOT NULL,
	[DISDESC] [varchar](20) NOT NULL,
	[GRADDESC] [varchar](20) NOT NULL,
	[MNFDESC] [varchar](30) NOT NULL,
	[PLANTDESC] [varchar](30) NOT NULL,
	[PGRPDESC] [varchar](20) NOT NULL,
	[CDATE] [varchar](10) NOT NULL,
	[TIME] [varchar](8) NOT NULL,
	[SUSER] [varchar](12) NOT NULL,
	[BLOCK_CT] [varchar](1) NOT NULL,
	[ROUTE] [varchar](40) NOT NULL,
	[CANCELDATE] [varchar](10) NOT NULL,
	[CANCELFLAG] [varchar](1) NOT NULL,
	[ZZLGORT1] [varchar](4) NOT NULL,
	[BZIRK] [varchar](6) NOT NULL,
	[VKBUR] [varchar](4) NOT NULL,
	[ZZZONE1] [varchar](10) NOT NULL,
	[ZZBRANCH] [varchar](4) NOT NULL,
	[PERNR_ER] [varchar](8) NOT NULL,
	[ENAME_ER] [varchar](40) NOT NULL,
	[PERNR_Y1] [varchar](8) NOT NULL,
	[ENAME_Y1] [varchar](40) NOT NULL,
	[PERNR_Y2] [varchar](8) NOT NULL,
	[ENAME_Y2] [varchar](40) NOT NULL,
	[PERNR_Y3] [varchar](8) NOT NULL,
	[ENAME_Y3] [varchar](40) NOT NULL,
	[PERNR_Y4] [varchar](8) NOT NULL,
	[ENAME_Y4] [varchar](40) NOT NULL,
	[PERNR_Y5] [varchar](8) NOT NULL,
	[ENAME_Y5] [varchar](40) NOT NULL,
	[PERNR_Y6] [varchar](8) NOT NULL,
	[ENAME_Y6] [varchar](40) NOT NULL,
	[PERNR_Y7] [varchar](8) NOT NULL,
	[ENAME_Y7] [varchar](40) NOT NULL,
	[PERNR_Y8] [varchar](8) NOT NULL,
	[ENAME_Y8] [varchar](40) NOT NULL,
	[UPFRNT_DISCOUNT] [decimal](16, 3) NOT NULL,
	[IND_PRI_FRT] [decimal](16, 3) NOT NULL,
	[SHIP_FRT_CHRGS] [decimal](16, 3) NOT NULL,
	[SHIP_HAND_CHRGS] [decimal](16, 3) NOT NULL,
	[ZCUST_GRP] [varchar](2) NOT NULL,
	[ZCUST_GRP_DESC] [varchar](20) NOT NULL,
	[Vc] [decimal](12, 3) NOT NULL,
	[ZsalePromValue] [decimal](12, 3) NOT NULL,
	[Waers] [varchar](5) NOT NULL,
	[Msehi] [varchar](3) NOT NULL,
	[PayFreight] [decimal](14, 3) NOT NULL,
	[ExFreight] [decimal](14, 3) NOT NULL,
 CONSTRAINT [PK_YREALIZATION] PRIMARY KEY CLUSTERED 
(
	[YREALIZATION_PKID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ZSD_LCOST_DATA_SRV]    Script Date: 2021/11/08 11:15:31 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ZSD_LCOST_DATA_SRV](
	[ZSD_LCOST_DATA_SRV_PKID] [bigint] IDENTITY(1,1) NOT NULL,
	[VBELN] [varchar](10) NOT NULL,
	[FKART] [varchar](4) NOT NULL,
	[FKDAT] [varchar](10) NOT NULL,
	[FKIMG] [decimal](13, 3) NOT NULL,
	[MEINS] [varchar](3) NOT NULL,
	[WERKS] [varchar](4) NOT NULL,
	[W_NAME1] [varchar](30) NOT NULL,
	[ZSOURCE] [varchar](2) NOT NULL,
	[ZSOURCED] [varchar](60) NOT NULL,
	[ZTRATYP] [varchar](2) NOT NULL,
	[ZTRATYPD] [varchar](60) NOT NULL,
	[KUNNR] [varchar](10) NOT NULL,
	[KUNNR_N] [varchar](35) NOT NULL,
	[KUNAG] [varchar](10) NOT NULL,
	[KUNAG_N] [varchar](35) NOT NULL,
	[PTNR] [varchar](10) NOT NULL,
	[PTNR_N] [varchar](35) NOT NULL,
	[SALSREP] [varchar](10) NOT NULL,
	[SALSREP_N] [varchar](35) NOT NULL,
	[REGIO] [varchar](3) NOT NULL,
	[REGIO_N] [varchar](20) NOT NULL,
	[DSTRC] [varchar](4) NOT NULL,
	[DSTRC_N] [varchar](20) NOT NULL,
	[BLOCK] [varchar](7) NOT NULL,
	[BLOCK_N] [varchar](20) NOT NULL,
	[DESTINT] [varchar](10) NOT NULL,
	[DESTINT_N] [varchar](20) NOT NULL,
	[KDGRP] [varchar](2) NOT NULL,
	[KTEXT] [varchar](20) NOT NULL,
	[PRIMARY_FRT] [decimal](14, 3) NOT NULL,
	[SECONDRY_FRT] [decimal](14, 3) NOT NULL,
	[RAKNO] [varchar](20) NOT NULL,
	[RAKPT] [varchar](6) NOT NULL,
	[MATKL] [varchar](9) NOT NULL,
	[LGORT] [varchar](4) NOT NULL,
	[LGOBE] [varchar](16) NOT NULL,
	[INCO1] [varchar](3) NOT NULL,
	[INCO2] [varchar](28) NOT NULL,
	[ULDG_CHGS] [decimal](9, 3) NOT NULL,
	[TRNS_CHGS] [decimal](9, 3) NOT NULL,
	[DPUL_CHGS] [decimal](9, 3) NOT NULL,
	[DPLD_CHGS] [decimal](9, 3) NOT NULL,
	[DIVR_CHGS] [decimal](9, 3) NOT NULL,
	[LDNG_CHGS] [decimal](9, 3) NOT NULL,
	[CFAG_CHGS] [decimal](9, 3) NOT NULL,
	[RKSR_CHGS] [decimal](9, 3) NOT NULL,
	[PULD_CHGS] [decimal](9, 3) NOT NULL,
	[RKCL_CHGS] [decimal](9, 3) NOT NULL,
	[SHNT_CHGS] [decimal](9, 3) NOT NULL,
	[RKCF_CHGS] [decimal](9, 3) NOT NULL,
	[BLND_CHGS] [decimal](9, 3) NOT NULL,
	[BLNB_CHGS] [decimal](9, 3) NOT NULL,
	[MISC_MISC] [decimal](9, 3) NOT NULL,
	[ZZZONE1] [varchar](10) NOT NULL,
	[ZZZONE1_N] [varchar](60) NOT NULL,
	[ZZBZIRK] [varchar](6) NOT NULL,
	[ZZBZIRK_N] [varchar](60) NOT NULL,
	[ZZREGIO] [varchar](3) NOT NULL,
	[ZZREGIO_N] [varchar](60) NOT NULL,
	[VKBUR] [varchar](4) NOT NULL,
	[VKBUR_N] [varchar](60) NOT NULL,
	[VKGRP] [varchar](3) NOT NULL,
	[VKGRP_N] [varchar](60) NOT NULL,
	[ZZBRANCH] [varchar](4) NOT NULL,
	[ZZBRANCH_N] [varchar](60) NOT NULL,
	[PDSTN] [decimal](13, 3) NOT NULL,
	[SDSTN] [decimal](13, 3) NOT NULL,
	[BLOCK_CT] [varchar](1) NOT NULL,
	[BELNR] [varchar](10) NOT NULL,
	[GJAHR] [varchar](4) NOT NULL,
	[INV_TYPE] [varchar](18) NOT NULL,
	[FRT_TYPE] [varchar](12) NOT NULL,
	[ZZVLFKZ] [varchar](1) NOT NULL,
	[SUPP_PLANT_NAME] [varchar](30) NOT NULL,
	[DEPO_RK_MVT] [varchar](20) NOT NULL,
	[IND_PRI_FRT] [decimal](16, 3) NOT NULL,
	[SHIP_FRT_CHRGS] [decimal](16, 3) NOT NULL,
	[SHIP_HAND_CHRGS] [decimal](16, 3) NOT NULL,
	[CLKMNFPLANT] [varchar](4) NOT NULL,
	[SUPPPLANT] [varchar](4) NOT NULL,
	[DISTANCE] [decimal](7, 2) NOT NULL,
	[INDPDISTANCE] [decimal](7, 2) NOT NULL,
	[CLK_PLT_NAME] [varchar](30) NOT NULL,
	[MNF_PLT_NAME] [varchar](30) NOT NULL,
	[GEIND_PLT] [varchar](4) NOT NULL,
	[GEIND_PLT_NAME] [varchar](30) NOT NULL,
	[SUPPL_DEPO] [varchar](4) NOT NULL,
	[SUPPL_DEPO_NAME] [varchar](30) NOT NULL,
	[WAERK] [varchar](5) NOT NULL,
	[RENT] [decimal](14, 3) NOT NULL,
	[RAKEDEMCHRG] [decimal](16, 3) NOT NULL,
	[LDISTANCE] [decimal](7, 2) NOT NULL,
	[LDISTANCE_CLK] [decimal](7, 2) NOT NULL,
	[MATNR] [varchar](18) NOT NULL,
	[VTEXT] [varchar](20) NOT NULL,
	[MATNR1] [varchar](18) NOT NULL,
	[MAKTX] [varchar](40) NOT NULL,
	[INCURREDCOST] [decimal](14, 3) NOT NULL,
	[UNINCURREDCOST] [decimal](14, 3) NOT NULL,
	[SH_REGIO] [varchar](3) NOT NULL,
	[SH_DSTRC] [varchar](4) NOT NULL,
	[SH_BLOCK] [varchar](7) NOT NULL,
	[SH_DESTINT] [varchar](10) NOT NULL,
	[KALKS] [varchar](1) NOT NULL,
	[DELIVERY_NO] [varchar](10) NOT NULL,
	[TKNUM] [varchar](10) NOT NULL,
	[MNFPLANT] [varchar](4) NOT NULL,
	[MNFDESC] [varchar](30) NOT NULL,
	[MVGR1] [varchar](3) NOT NULL,
	[GROSSTURN] [decimal](16, 3) NOT NULL,
	[NETTURN] [decimal](16, 3) NOT NULL,
	[NAKEDREAL] [decimal](16, 3) NOT NULL,
	[TRANS_INCENTIVE] [decimal](16, 3) NOT NULL,
	[PLT_FRT] [decimal](16, 3) NOT NULL,
	[SP_REGIO] [varchar](3) NOT NULL,
	[SP_DSTRC] [varchar](4) NOT NULL,
	[SP_BLOCK] [varchar](7) NOT NULL,
	[SP_DESTINT] [varchar](10) NOT NULL,
	[TRAID] [varchar](20) NOT NULL,
	[TRUCK_TYPE] [varchar](20) NOT NULL,
	[EWB_NO] [varchar](12) NOT NULL,
	[EDATE] [varchar](10) NOT NULL,
	[EVDATE] [varchar](10) NOT NULL,
	[STEUC] [varchar](16) NOT NULL,
	[PAID_PRICE] [decimal](12, 3) NOT NULL,
	[KALKS_DESC] [varchar](20) NOT NULL,
	[SP_REGIO_DESC] [varchar](20) NOT NULL,
	[SP_DSTRC_DESC] [varchar](20) NOT NULL,
	[SP_BLOCK_DESC] [varchar](20) NOT NULL,
	[SP_DESTINT_DESC] [varchar](20) NOT NULL,
	[MF_PLANT_TYPE] [varchar](60) NOT NULL,
	[TOTAL_TDC_COST] [decimal](14, 3) NOT NULL,
	[TOTAL_DISTANCE] [decimal](9, 2) NOT NULL,
	[DEPOT_IND_FRIEGHT] [decimal](16, 3) NOT NULL,
	[TOTAL_INVOICE_FRT] [decimal](14, 3) NOT NULL,
	[ROAD_PF_INCURRED] [decimal](14, 3) NOT NULL,
	[ROAD_PF_UNINCURRED] [decimal](14, 3) NOT NULL,
	[ROAD_SF_INCURRED] [decimal](14, 3) NOT NULL,
	[ROAD_SF_UNINCURRED] [decimal](14, 3) NOT NULL,
	[RAIL_PF_INCURRED] [decimal](14, 3) NOT NULL,
	[RAIL_PF_UNINCURRED] [decimal](14, 3) NOT NULL,
	[DRDL_CHGS] [decimal](9, 3) NOT NULL,
	[DB_LAB_CHGS] [decimal](9, 3) NOT NULL,
	[ZINV_CANCEL] [varchar](1) NOT NULL,
	[SH_DESTINT_DESC] [varchar](20) NOT NULL,
	[SHIP_DISTANCE] [decimal](13, 3) NOT NULL,
 CONSTRAINT [PK_ZSD_LCOST_DATA_SRV] PRIMARY KEY CLUSTERED 
(
	[ZSD_LCOST_DATA_SRV_PKID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ZSD_REAL_DATA_SRV_REAL]    Script Date: 2021/11/08 11:15:31 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO