Imports System
Imports DataDynamics.ActiveReports
Imports DataDynamics.ActiveReports.Document

Public Class R_Kanyu_iPad
Inherits ActiveReport

    Dim WK_prt_date As Date
    Dim WK_str As String

    Public Sub New()
        MyBase.New()
        InitializeReport()

        Dim Culture As Globalization.CultureInfo = New Globalization.CultureInfo("ja-JP", True)
        Culture.DateTimeFormat.Calendar = New Globalization.JapaneseCalendar
        WK_prt_date = Now.Date
        prt_date.Text = "サービス証発行日　：" & WK_prt_date.ToString("yyyy年M月d日")

    End Sub
#Region "ActiveReports Designer generated code"
    Private WithEvents Detail As DataDynamics.ActiveReports.Detail = Nothing
	Private prt_date As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label As DataDynamics.ActiveReports.Label = Nothing
	Private Label3 As DataDynamics.ActiveReports.Label = Nothing
	Private code As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label5 As DataDynamics.ActiveReports.Label = Nothing
	Private Label45 As DataDynamics.ActiveReports.Label = Nothing
	Private adrs1 As DataDynamics.ActiveReports.TextBox = Nothing
	Private univ_name As DataDynamics.ActiveReports.TextBox = Nothing
	Private user_name As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label12 As DataDynamics.ActiveReports.Label = Nothing
	Private s_no As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label9 As DataDynamics.ActiveReports.Label = Nothing
	Private makr_wrn_stat As DataDynamics.ActiveReports.TextBox = Nothing
	Private wrn_end As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label40 As DataDynamics.ActiveReports.Label = Nothing
	Private Label1 As DataDynamics.ActiveReports.Label = Nothing
	Private Label2 As DataDynamics.ActiveReports.Label = Nothing
	Private Label4 As DataDynamics.ActiveReports.Label = Nothing
	Private Label6 As DataDynamics.ActiveReports.Label = Nothing
	Private Label7 As DataDynamics.ActiveReports.Label = Nothing
	Private Label8 As DataDynamics.ActiveReports.Label = Nothing
	Private Label10 As DataDynamics.ActiveReports.Label = Nothing
	Private Label11 As DataDynamics.ActiveReports.Label = Nothing
	Private Label13 As DataDynamics.ActiveReports.Label = Nothing
	Private Label14 As DataDynamics.ActiveReports.Label = Nothing
	Private Label15 As DataDynamics.ActiveReports.Label = Nothing
	Private Label16 As DataDynamics.ActiveReports.Label = Nothing
	Private Label17 As DataDynamics.ActiveReports.Label = Nothing
	Private Label18 As DataDynamics.ActiveReports.Label = Nothing
	Private Label19 As DataDynamics.ActiveReports.Label = Nothing
	Private Label20 As DataDynamics.ActiveReports.Label = Nothing
	Private Label21 As DataDynamics.ActiveReports.Label = Nothing
	Private Label22 As DataDynamics.ActiveReports.Label = Nothing
	Private Label23 As DataDynamics.ActiveReports.Label = Nothing
	Private Label24 As DataDynamics.ActiveReports.Label = Nothing
	Private Label25 As DataDynamics.ActiveReports.Label = Nothing
	Private Label26 As DataDynamics.ActiveReports.Label = Nothing
	Private Label27 As DataDynamics.ActiveReports.Label = Nothing
	Private Label28 As DataDynamics.ActiveReports.Label = Nothing
	Private Label29 As DataDynamics.ActiveReports.Label = Nothing
	Private Label30 As DataDynamics.ActiveReports.Label = Nothing
	Private Label31 As DataDynamics.ActiveReports.Label = Nothing
	Private Label32 As DataDynamics.ActiveReports.Label = Nothing
	Private Label33 As DataDynamics.ActiveReports.Label = Nothing
	Private Label34 As DataDynamics.ActiveReports.Label = Nothing
	Private Label35 As DataDynamics.ActiveReports.Label = Nothing
	Private Label36 As DataDynamics.ActiveReports.Label = Nothing
	Private Label37 As DataDynamics.ActiveReports.Label = Nothing
	Private Label38 As DataDynamics.ActiveReports.Label = Nothing
	Private Label39 As DataDynamics.ActiveReports.Label = Nothing
	Private Label41 As DataDynamics.ActiveReports.Label = Nothing
	Private Label42 As DataDynamics.ActiveReports.Label = Nothing
	Private Label43 As DataDynamics.ActiveReports.Label = Nothing
	Private Label44 As DataDynamics.ActiveReports.Label = Nothing
	Private Label46 As DataDynamics.ActiveReports.Label = Nothing
	Private Label47 As DataDynamics.ActiveReports.Label = Nothing
	Private Label48 As DataDynamics.ActiveReports.Label = Nothing
	Private Label49 As DataDynamics.ActiveReports.Label = Nothing
	Private Label50 As DataDynamics.ActiveReports.Label = Nothing
	Private Label51 As DataDynamics.ActiveReports.Label = Nothing
	Private Label52 As DataDynamics.ActiveReports.Label = Nothing
	Private Label53 As DataDynamics.ActiveReports.Label = Nothing
	Private Label54 As DataDynamics.ActiveReports.Label = Nothing
	Private Label55 As DataDynamics.ActiveReports.Label = Nothing
	Private Label56 As DataDynamics.ActiveReports.Label = Nothing
	Private Label57 As DataDynamics.ActiveReports.Label = Nothing
	Private Label58 As DataDynamics.ActiveReports.Label = Nothing
	Private Label59 As DataDynamics.ActiveReports.Label = Nothing
	Private Label60 As DataDynamics.ActiveReports.Label = Nothing
	Private Label62 As DataDynamics.ActiveReports.Label = Nothing
	Private Label63 As DataDynamics.ActiveReports.Label = Nothing
	Private Label64 As DataDynamics.ActiveReports.Label = Nothing
	Private Label65 As DataDynamics.ActiveReports.Label = Nothing
	Private Label66 As DataDynamics.ActiveReports.Label = Nothing
	Private Label67 As DataDynamics.ActiveReports.Label = Nothing
	Private Label68 As DataDynamics.ActiveReports.Label = Nothing
	Private Label69 As DataDynamics.ActiveReports.Label = Nothing
	Private Label70 As DataDynamics.ActiveReports.Label = Nothing
	Private Label71 As DataDynamics.ActiveReports.Label = Nothing
	Private Label72 As DataDynamics.ActiveReports.Label = Nothing
	Private Label73 As DataDynamics.ActiveReports.Label = Nothing
	Private Label74 As DataDynamics.ActiveReports.Label = Nothing
	Private Label75 As DataDynamics.ActiveReports.Label = Nothing
	Private Label76 As DataDynamics.ActiveReports.Label = Nothing
	Private Label77 As DataDynamics.ActiveReports.Label = Nothing
	Private Label78 As DataDynamics.ActiveReports.Label = Nothing
	Private Label79 As DataDynamics.ActiveReports.Label = Nothing
	Private Label80 As DataDynamics.ActiveReports.Label = Nothing
	Private Label81 As DataDynamics.ActiveReports.Label = Nothing
	Private Label82 As DataDynamics.ActiveReports.Label = Nothing
	Private Label83 As DataDynamics.ActiveReports.Label = Nothing
	Private Label84 As DataDynamics.ActiveReports.Label = Nothing
	Private Label85 As DataDynamics.ActiveReports.Label = Nothing
	Private Label86 As DataDynamics.ActiveReports.Label = Nothing
	Private Label87 As DataDynamics.ActiveReports.Label = Nothing
	Private Label88 As DataDynamics.ActiveReports.Label = Nothing
	Private Label89 As DataDynamics.ActiveReports.Label = Nothing
	Private Label90 As DataDynamics.ActiveReports.Label = Nothing
	Private Label91 As DataDynamics.ActiveReports.Label = Nothing
	Private Label92 As DataDynamics.ActiveReports.Label = Nothing
	Private Label93 As DataDynamics.ActiveReports.Label = Nothing
	Private Label94 As DataDynamics.ActiveReports.Label = Nothing
	Private Label95 As DataDynamics.ActiveReports.Label = Nothing
	Private Label96 As DataDynamics.ActiveReports.Label = Nothing
	Private Label97 As DataDynamics.ActiveReports.Label = Nothing
	Private Label98 As DataDynamics.ActiveReports.Label = Nothing
	Private Label99 As DataDynamics.ActiveReports.Label = Nothing
	Private Label100 As DataDynamics.ActiveReports.Label = Nothing
	Private Label101 As DataDynamics.ActiveReports.Label = Nothing
	Private Label102 As DataDynamics.ActiveReports.Label = Nothing
	Private Label103 As DataDynamics.ActiveReports.Label = Nothing
	Private Label104 As DataDynamics.ActiveReports.Label = Nothing
	Private Label105 As DataDynamics.ActiveReports.Label = Nothing
	Private Label106 As DataDynamics.ActiveReports.Label = Nothing
	Private Shape1 As DataDynamics.ActiveReports.Shape = Nothing
	Private Shape As DataDynamics.ActiveReports.Shape = Nothing
	Private Shape2 As DataDynamics.ActiveReports.Shape = Nothing
	Private Line As DataDynamics.ActiveReports.Line = Nothing
	Private Line1 As DataDynamics.ActiveReports.Line = Nothing
	Private Line2 As DataDynamics.ActiveReports.Line = Nothing
	Private Line3 As DataDynamics.ActiveReports.Line = Nothing
	Private Label107 As DataDynamics.ActiveReports.Label = Nothing
	Private Shape4 As DataDynamics.ActiveReports.Shape = Nothing
	Private Picture5 As DataDynamics.ActiveReports.Picture = Nothing
	Private Label108 As DataDynamics.ActiveReports.Label = Nothing
	Private Label109 As DataDynamics.ActiveReports.Label = Nothing
	Private Label110 As DataDynamics.ActiveReports.Label = Nothing
	Private Picture As DataDynamics.ActiveReports.Picture = Nothing
	Private TextBox As DataDynamics.ActiveReports.TextBox = Nothing
	Private Label111 As DataDynamics.ActiveReports.Label = Nothing
	Private Shape3 As DataDynamics.ActiveReports.Shape = Nothing
	Private Label61 As DataDynamics.ActiveReports.Label = Nothing
	Private Label112 As DataDynamics.ActiveReports.Label = Nothing
	Public Sub InitializeReport()
		Me.LoadLayout(Me.GetType, "nQGCare.R_Kanyu_iPad.rpx")
		Me.Detail = CType(Me.Sections("Detail"),DataDynamics.ActiveReports.Detail)
		Me.prt_date = CType(Me.Detail.Controls(0),DataDynamics.ActiveReports.TextBox)
		Me.Label = CType(Me.Detail.Controls(1),DataDynamics.ActiveReports.Label)
		Me.Label3 = CType(Me.Detail.Controls(2),DataDynamics.ActiveReports.Label)
		Me.code = CType(Me.Detail.Controls(3),DataDynamics.ActiveReports.TextBox)
		Me.Label5 = CType(Me.Detail.Controls(4),DataDynamics.ActiveReports.Label)
		Me.Label45 = CType(Me.Detail.Controls(5),DataDynamics.ActiveReports.Label)
		Me.adrs1 = CType(Me.Detail.Controls(6),DataDynamics.ActiveReports.TextBox)
		Me.univ_name = CType(Me.Detail.Controls(7),DataDynamics.ActiveReports.TextBox)
		Me.user_name = CType(Me.Detail.Controls(8),DataDynamics.ActiveReports.TextBox)
		Me.Label12 = CType(Me.Detail.Controls(9),DataDynamics.ActiveReports.Label)
		Me.s_no = CType(Me.Detail.Controls(10),DataDynamics.ActiveReports.TextBox)
		Me.Label9 = CType(Me.Detail.Controls(11),DataDynamics.ActiveReports.Label)
		Me.makr_wrn_stat = CType(Me.Detail.Controls(12),DataDynamics.ActiveReports.TextBox)
		Me.wrn_end = CType(Me.Detail.Controls(13),DataDynamics.ActiveReports.TextBox)
		Me.Label40 = CType(Me.Detail.Controls(14),DataDynamics.ActiveReports.Label)
		Me.Label1 = CType(Me.Detail.Controls(15),DataDynamics.ActiveReports.Label)
		Me.Label2 = CType(Me.Detail.Controls(16),DataDynamics.ActiveReports.Label)
		Me.Label4 = CType(Me.Detail.Controls(17),DataDynamics.ActiveReports.Label)
		Me.Label6 = CType(Me.Detail.Controls(18),DataDynamics.ActiveReports.Label)
		Me.Label7 = CType(Me.Detail.Controls(19),DataDynamics.ActiveReports.Label)
		Me.Label8 = CType(Me.Detail.Controls(20),DataDynamics.ActiveReports.Label)
		Me.Label10 = CType(Me.Detail.Controls(21),DataDynamics.ActiveReports.Label)
		Me.Label11 = CType(Me.Detail.Controls(22),DataDynamics.ActiveReports.Label)
		Me.Label13 = CType(Me.Detail.Controls(23),DataDynamics.ActiveReports.Label)
		Me.Label14 = CType(Me.Detail.Controls(24),DataDynamics.ActiveReports.Label)
		Me.Label15 = CType(Me.Detail.Controls(25),DataDynamics.ActiveReports.Label)
		Me.Label16 = CType(Me.Detail.Controls(26),DataDynamics.ActiveReports.Label)
		Me.Label17 = CType(Me.Detail.Controls(27),DataDynamics.ActiveReports.Label)
		Me.Label18 = CType(Me.Detail.Controls(28),DataDynamics.ActiveReports.Label)
		Me.Label19 = CType(Me.Detail.Controls(29),DataDynamics.ActiveReports.Label)
		Me.Label20 = CType(Me.Detail.Controls(30),DataDynamics.ActiveReports.Label)
		Me.Label21 = CType(Me.Detail.Controls(31),DataDynamics.ActiveReports.Label)
		Me.Label22 = CType(Me.Detail.Controls(32),DataDynamics.ActiveReports.Label)
		Me.Label23 = CType(Me.Detail.Controls(33),DataDynamics.ActiveReports.Label)
		Me.Label24 = CType(Me.Detail.Controls(34),DataDynamics.ActiveReports.Label)
		Me.Label25 = CType(Me.Detail.Controls(35),DataDynamics.ActiveReports.Label)
		Me.Label26 = CType(Me.Detail.Controls(36),DataDynamics.ActiveReports.Label)
		Me.Label27 = CType(Me.Detail.Controls(37),DataDynamics.ActiveReports.Label)
		Me.Label28 = CType(Me.Detail.Controls(38),DataDynamics.ActiveReports.Label)
		Me.Label29 = CType(Me.Detail.Controls(39),DataDynamics.ActiveReports.Label)
		Me.Label30 = CType(Me.Detail.Controls(40),DataDynamics.ActiveReports.Label)
		Me.Label31 = CType(Me.Detail.Controls(41),DataDynamics.ActiveReports.Label)
		Me.Label32 = CType(Me.Detail.Controls(42),DataDynamics.ActiveReports.Label)
		Me.Label33 = CType(Me.Detail.Controls(43),DataDynamics.ActiveReports.Label)
		Me.Label34 = CType(Me.Detail.Controls(44),DataDynamics.ActiveReports.Label)
		Me.Label35 = CType(Me.Detail.Controls(45),DataDynamics.ActiveReports.Label)
		Me.Label36 = CType(Me.Detail.Controls(46),DataDynamics.ActiveReports.Label)
		Me.Label37 = CType(Me.Detail.Controls(47),DataDynamics.ActiveReports.Label)
		Me.Label38 = CType(Me.Detail.Controls(48),DataDynamics.ActiveReports.Label)
		Me.Label39 = CType(Me.Detail.Controls(49),DataDynamics.ActiveReports.Label)
		Me.Label41 = CType(Me.Detail.Controls(50),DataDynamics.ActiveReports.Label)
		Me.Label42 = CType(Me.Detail.Controls(51),DataDynamics.ActiveReports.Label)
		Me.Label43 = CType(Me.Detail.Controls(52),DataDynamics.ActiveReports.Label)
		Me.Label44 = CType(Me.Detail.Controls(53),DataDynamics.ActiveReports.Label)
		Me.Label46 = CType(Me.Detail.Controls(54),DataDynamics.ActiveReports.Label)
		Me.Label47 = CType(Me.Detail.Controls(55),DataDynamics.ActiveReports.Label)
		Me.Label48 = CType(Me.Detail.Controls(56),DataDynamics.ActiveReports.Label)
		Me.Label49 = CType(Me.Detail.Controls(57),DataDynamics.ActiveReports.Label)
		Me.Label50 = CType(Me.Detail.Controls(58),DataDynamics.ActiveReports.Label)
		Me.Label51 = CType(Me.Detail.Controls(59),DataDynamics.ActiveReports.Label)
		Me.Label52 = CType(Me.Detail.Controls(60),DataDynamics.ActiveReports.Label)
		Me.Label53 = CType(Me.Detail.Controls(61),DataDynamics.ActiveReports.Label)
		Me.Label54 = CType(Me.Detail.Controls(62),DataDynamics.ActiveReports.Label)
		Me.Label55 = CType(Me.Detail.Controls(63),DataDynamics.ActiveReports.Label)
		Me.Label56 = CType(Me.Detail.Controls(64),DataDynamics.ActiveReports.Label)
		Me.Label57 = CType(Me.Detail.Controls(65),DataDynamics.ActiveReports.Label)
		Me.Label58 = CType(Me.Detail.Controls(66),DataDynamics.ActiveReports.Label)
		Me.Label59 = CType(Me.Detail.Controls(67),DataDynamics.ActiveReports.Label)
		Me.Label60 = CType(Me.Detail.Controls(68),DataDynamics.ActiveReports.Label)
		Me.Label62 = CType(Me.Detail.Controls(69),DataDynamics.ActiveReports.Label)
		Me.Label63 = CType(Me.Detail.Controls(70),DataDynamics.ActiveReports.Label)
		Me.Label64 = CType(Me.Detail.Controls(71),DataDynamics.ActiveReports.Label)
		Me.Label65 = CType(Me.Detail.Controls(72),DataDynamics.ActiveReports.Label)
		Me.Label66 = CType(Me.Detail.Controls(73),DataDynamics.ActiveReports.Label)
		Me.Label67 = CType(Me.Detail.Controls(74),DataDynamics.ActiveReports.Label)
		Me.Label68 = CType(Me.Detail.Controls(75),DataDynamics.ActiveReports.Label)
		Me.Label69 = CType(Me.Detail.Controls(76),DataDynamics.ActiveReports.Label)
		Me.Label70 = CType(Me.Detail.Controls(77),DataDynamics.ActiveReports.Label)
		Me.Label71 = CType(Me.Detail.Controls(78),DataDynamics.ActiveReports.Label)
		Me.Label72 = CType(Me.Detail.Controls(79),DataDynamics.ActiveReports.Label)
		Me.Label73 = CType(Me.Detail.Controls(80),DataDynamics.ActiveReports.Label)
		Me.Label74 = CType(Me.Detail.Controls(81),DataDynamics.ActiveReports.Label)
		Me.Label75 = CType(Me.Detail.Controls(82),DataDynamics.ActiveReports.Label)
		Me.Label76 = CType(Me.Detail.Controls(83),DataDynamics.ActiveReports.Label)
		Me.Label77 = CType(Me.Detail.Controls(84),DataDynamics.ActiveReports.Label)
		Me.Label78 = CType(Me.Detail.Controls(85),DataDynamics.ActiveReports.Label)
		Me.Label79 = CType(Me.Detail.Controls(86),DataDynamics.ActiveReports.Label)
		Me.Label80 = CType(Me.Detail.Controls(87),DataDynamics.ActiveReports.Label)
		Me.Label81 = CType(Me.Detail.Controls(88),DataDynamics.ActiveReports.Label)
		Me.Label82 = CType(Me.Detail.Controls(89),DataDynamics.ActiveReports.Label)
		Me.Label83 = CType(Me.Detail.Controls(90),DataDynamics.ActiveReports.Label)
		Me.Label84 = CType(Me.Detail.Controls(91),DataDynamics.ActiveReports.Label)
		Me.Label85 = CType(Me.Detail.Controls(92),DataDynamics.ActiveReports.Label)
		Me.Label86 = CType(Me.Detail.Controls(93),DataDynamics.ActiveReports.Label)
		Me.Label87 = CType(Me.Detail.Controls(94),DataDynamics.ActiveReports.Label)
		Me.Label88 = CType(Me.Detail.Controls(95),DataDynamics.ActiveReports.Label)
		Me.Label89 = CType(Me.Detail.Controls(96),DataDynamics.ActiveReports.Label)
		Me.Label90 = CType(Me.Detail.Controls(97),DataDynamics.ActiveReports.Label)
		Me.Label91 = CType(Me.Detail.Controls(98),DataDynamics.ActiveReports.Label)
		Me.Label92 = CType(Me.Detail.Controls(99),DataDynamics.ActiveReports.Label)
		Me.Label93 = CType(Me.Detail.Controls(100),DataDynamics.ActiveReports.Label)
		Me.Label94 = CType(Me.Detail.Controls(101),DataDynamics.ActiveReports.Label)
		Me.Label95 = CType(Me.Detail.Controls(102),DataDynamics.ActiveReports.Label)
		Me.Label96 = CType(Me.Detail.Controls(103),DataDynamics.ActiveReports.Label)
		Me.Label97 = CType(Me.Detail.Controls(104),DataDynamics.ActiveReports.Label)
		Me.Label98 = CType(Me.Detail.Controls(105),DataDynamics.ActiveReports.Label)
		Me.Label99 = CType(Me.Detail.Controls(106),DataDynamics.ActiveReports.Label)
		Me.Label100 = CType(Me.Detail.Controls(107),DataDynamics.ActiveReports.Label)
		Me.Label101 = CType(Me.Detail.Controls(108),DataDynamics.ActiveReports.Label)
		Me.Label102 = CType(Me.Detail.Controls(109),DataDynamics.ActiveReports.Label)
		Me.Label103 = CType(Me.Detail.Controls(110),DataDynamics.ActiveReports.Label)
		Me.Label104 = CType(Me.Detail.Controls(111),DataDynamics.ActiveReports.Label)
		Me.Label105 = CType(Me.Detail.Controls(112),DataDynamics.ActiveReports.Label)
		Me.Label106 = CType(Me.Detail.Controls(113),DataDynamics.ActiveReports.Label)
		Me.Shape1 = CType(Me.Detail.Controls(114),DataDynamics.ActiveReports.Shape)
		Me.Shape = CType(Me.Detail.Controls(115),DataDynamics.ActiveReports.Shape)
		Me.Shape2 = CType(Me.Detail.Controls(116),DataDynamics.ActiveReports.Shape)
		Me.Line = CType(Me.Detail.Controls(117),DataDynamics.ActiveReports.Line)
		Me.Line1 = CType(Me.Detail.Controls(118),DataDynamics.ActiveReports.Line)
		Me.Line2 = CType(Me.Detail.Controls(119),DataDynamics.ActiveReports.Line)
		Me.Line3 = CType(Me.Detail.Controls(120),DataDynamics.ActiveReports.Line)
		Me.Label107 = CType(Me.Detail.Controls(121),DataDynamics.ActiveReports.Label)
		Me.Shape4 = CType(Me.Detail.Controls(122),DataDynamics.ActiveReports.Shape)
		Me.Picture5 = CType(Me.Detail.Controls(123),DataDynamics.ActiveReports.Picture)
		Me.Label108 = CType(Me.Detail.Controls(124),DataDynamics.ActiveReports.Label)
		Me.Label109 = CType(Me.Detail.Controls(125),DataDynamics.ActiveReports.Label)
		Me.Label110 = CType(Me.Detail.Controls(126),DataDynamics.ActiveReports.Label)
		Me.Picture = CType(Me.Detail.Controls(127),DataDynamics.ActiveReports.Picture)
		Me.TextBox = CType(Me.Detail.Controls(128),DataDynamics.ActiveReports.TextBox)
		Me.Label111 = CType(Me.Detail.Controls(129),DataDynamics.ActiveReports.Label)
		Me.Shape3 = CType(Me.Detail.Controls(130),DataDynamics.ActiveReports.Shape)
		Me.Label61 = CType(Me.Detail.Controls(131),DataDynamics.ActiveReports.Label)
		Me.Label112 = CType(Me.Detail.Controls(132),DataDynamics.ActiveReports.Label)
	End Sub

#End Region
End Class
