'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Apple_Customer_Information

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''divcard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divcard As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCustomer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblhidPoDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblhidPoDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPoNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPoNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drpServiceType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpServiceType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtInvoiceNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGsxNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGsxNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddressLine1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressLine1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddressLine2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressLine2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtZip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkRepairCenter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRepairCenter As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTelephone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephone As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMobile As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGstin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGstin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkShipped control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShipped As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''divShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divShip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCustomerNameShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerNameShip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddressLine1Ship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressLine1Ship As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddressLine2Ship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressLine2Ship As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCityShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCityShip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStateShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStateShip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtZipShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZipShip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmailShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailShip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkReception control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReception As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkInternalInspection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInternalInspection As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSignatureInServiceEstimate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSignatureInServiceEstimate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWholeServiceFeeCollection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWholeServiceFeeCollection As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkGsxOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGsxOrder As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRepair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRepair As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRemainingAmountCollection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRemainingAmountCollection As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkLoanerCollection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkLoanerCollection As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkServiceReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkServiceReport As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTaxInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTaxInvoice As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtTelephoneShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneShip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMobileShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMobileShip As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProduct As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtActionTaken control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActionTaken As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtModel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerialNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtImei1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImei1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtImei2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImei2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDateOfPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateOfPurchase As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAccessoryNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessoryNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompTia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompTia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompTiaModifier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompTiaModifier As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCalculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalculation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''drpLabourAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpLabourAmount As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLabourAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourAmountTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourAmountTemp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourHsnSacCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourHsnSacCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourDiscount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourSales As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourTax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourSGST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourSGST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourCGST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourCGST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourIGST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourIGST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQty1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQty1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkSerialPart1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSerialPart1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkst1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkst1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''drpSt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpSt1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPartDetails1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartDetails1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHsnSac1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHsnSac1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCost1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCost1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiscount1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscount1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSalesPrice1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesPrice1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPart1Tax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPart1Tax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSGST1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSGST1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCGST1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCGST1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIGST1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIGST1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotal1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQty2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQty2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkSerialPart2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSerialPart2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkst2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkst2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''drpSt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpSt2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPartDetails2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartDetails2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHsnSac2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHsnSac2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCost2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCost2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiscount2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscount2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSalesPrice2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesPrice2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPart2Tax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPart2Tax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSGST2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSGST2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCGST2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCGST2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIGST2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIGST2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotal2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotal2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartNo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNo3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQty3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQty3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkSerialPart3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSerialPart3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkst3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkst3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''drpSt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpSt3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPartDetails3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartDetails3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHsnSac3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHsnSac3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCost3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCost3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiscount3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscount3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSalesPrice3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesPrice3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPart3Tax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPart3Tax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSGST3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSGST3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCGST3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCGST3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIGST3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIGST3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotal3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotal3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartNo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartNo4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQty4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQty4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkSerialPart4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSerialPart4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkst4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkst4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''drpSt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpSt4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPartDetails4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartDetails4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHsnSac4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHsnSac4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCost4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCost4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiscount4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscount4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSalesPrice4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSalesPrice4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPart4Tax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPart4Tax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSGST4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSGST4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCGST4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCGST4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIGST4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIGST4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotal4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotal4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartQtyAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartQtyAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartCostAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartCostAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartDiscountAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartDiscountAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartSalesAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartSalesAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartSGSTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartSGSTAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartCGSTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartCGSTAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartIGSTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartIGSTAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPartTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPartTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherQtyAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherQtyAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherDiscount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherSales As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherTax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherTax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherSGST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherSGST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherCGST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherCGST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherIGST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherIGST As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherTotal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalQty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalCostAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalCostAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiscountAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscountAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalSalesAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalSalesAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalSGSTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalSGSTAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalCGSTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalCGSTAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalIGSTAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalIGSTAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAdvance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdvance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBalance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGSXCloseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGSXCloseDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drpCompStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpCompStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDeliveryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeliveryDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCompDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drpDenomination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpDenomination As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtEstimatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstimatedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLastUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastUser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLastUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastUpdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''save2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents save2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnComplete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDelivered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelivered As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnEstimate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEstimate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btninvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btninvoice As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Btndiagonis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btndiagonis As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbl01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl01 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
