'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Apple_Labour_Create

    '''<summary>
    '''divcard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divcard As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCustomer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtUploadUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUploadUser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUploadDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUploadDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShiptobranchcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShiptobranchcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtShiptobranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtShiptobranch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourtype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourtype As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourdescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourdescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourdetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourdetails As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLabourcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabourcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmount100 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount100 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmount150 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount150 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmount170 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount170 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmount180 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount180 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHSNSAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHSNSAC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIPAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIPAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFileName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSRCFilename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSRCFilename As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Back control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Back As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''create control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents create As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
