'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Popup

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''CRTDT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CRTDT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCRTDT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCRTDT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCRTCD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCRTCD As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUPDDT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUPDDT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUPDCD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUPDCD As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblUPDPG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUPDPG As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblDELFG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDELFG As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_name As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_info control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_info As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_manager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_manager As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_tel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_add1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_add1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_add2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_add2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_add3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_add3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblzip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblzip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lble_mail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lble_mail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_service control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_service As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblopen_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblopen_time As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblclose_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblclose_time As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblopening_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblopening_date As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblclosing_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblclosing_date As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_code As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblship_mark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblship_mark As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblitem_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblitem_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblitem_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblitem_2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmess_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmess_1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmess_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmess_2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblmess_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmess_3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblregi_deposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblregi_deposit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPO_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPO_no As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblinspection1_start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinspection1_start As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblinspection1_end control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinspection1_end As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblinspection2_start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinspection2_start As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblinspection2_end control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinspection2_end As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblinspection3_start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinspection3_start As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblinspection3_end control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinspection3_end As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblopen_start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblopen_start As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblopen_end control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblopen_end As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblclose_start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblclose_start As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblclose_end control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblclose_end As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGSTIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGSTIN As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblParent_Ship_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParent_Ship_Name As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblIsChildShip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIsChildShip As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRpaClientUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRpaClientUserId As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRpaClientPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRpaClientPwd As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblpwdupdateddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpwdupdateddate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblIsShipCodeChanged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIsShipCodeChanged As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
